export const mockShipmentRecapData = [
  {
    shipment_recap_id: '092025-1',
    co_group: 'TTA',
    shipment_number: 'MT-4896R',
    vessel_operator_name: 'PT. DINASTI MARITIM ABADI',
    vessel_name: 'TB. PHU DMA 098',
    barge_name: 'BG Andalas BMT',
    status: 'Locked',
  },
  {
    shipment_recap_id: '092025-2',
    co_group: 'NLG',
    shipment_number: 'MT-6721A',
    vessel_operator_name: 'PT. SAMUDERA LINES',
    vessel_name: 'MV. Nusantara 01',
    barge_name: 'BG Laut Indah',
    status: 'Draft',
  },
  {
    shipment_recap_id: '092025-3',
    co_group: 'GMC',
    shipment_number: 'MT-9032X',
    vessel_operator_name: 'PT. GLOBAL MARITIM CARGO',
    vessel_name: 'MV. Ocean Star',
    barge_name: 'BG Sumber Makmur',
    status: 'Port Changed',
  },
  {
    shipment_recap_id: '092025-4',
    co_group: 'LTI',
    shipment_number: 'MT-1147B',
    vessel_operator_name: 'PT. LAUTAN TIMUR INDONESIA',
    vessel_name: 'MV. Borneo Spirit',
    barge_name: 'BG Borneo Jaya',
    status: 'Locked',
  },
  {
    shipment_recap_id: '092025-5',
    co_group: 'SMP',
    shipment_number: 'MT-5578Z',
    vessel_operator_name: 'PT. SAMPURNA MARITIM',
    vessel_name: 'TB. Sumber Cahaya',
    barge_name: 'BG Cahaya Abadi',
    status: 'Draft',
  },
];
